execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/archer" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/archer")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/archer" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/archer")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/boteditor" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/boteditor")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/checker" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/checker")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/checker" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/checker")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/geometree" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/geometree")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/geometree" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/geometree")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/igraph" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/igraph")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/igraph" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/igraph")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/hv3" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/hv3")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/hv3" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/hv3")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lod" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/lod")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/mged" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/mged")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/plot3-dm" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/plot3-dm")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/plot3-dm" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/plot3-dm")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs/scripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs/scripts")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/sdialogs")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/shotvis" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/shotvis")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/shotvis" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/shotvis")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets/scripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets/scripts")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/swidgets")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/tcllib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/tcllib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/tcllib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/tcllib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/util" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/util")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/util" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/util")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard/lib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard/lib")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/pkg_mkIndex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard")
endif()
execute_process(COMMAND ${BTCLSH} "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CMakeTmp/auto_mkindex.tcl" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process D:/a/brlcad_winci/brlcad_winci/brlcad_build/share/tclscripts/rtwizard")
endif()
