# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress-rtwiz_m35_A]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_A.cmake")
set_tests_properties([=[regress-rtwiz_m35_A]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;36;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_B]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_B.cmake")
set_tests_properties([=[regress-rtwiz_m35_B]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;44;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_C]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_C.cmake")
set_tests_properties([=[regress-rtwiz_m35_C]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;52;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_D]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_D.cmake")
set_tests_properties([=[regress-rtwiz_m35_D]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;60;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_E]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_E.cmake")
set_tests_properties([=[regress-rtwiz_m35_E]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;68;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_F]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_F.cmake")
set_tests_properties([=[regress-rtwiz_m35_F]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;76;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_edge_only]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_edge_only.cmake")
set_tests_properties([=[regress-rtwiz_m35_edge_only]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;84;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_edge_only_color]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rtwizard.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/rtwizard/regress-rtwiz_m35_edge_only_color.cmake")
set_tests_properties([=[regress-rtwiz_m35_edge_only_color]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;92;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/rtwizard/CMakeLists.txt;0;")
