# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "D:/a/brlcad_winci/brlcad_winci/brlcad;D:/a/brlcad_winci/brlcad_winci/brlcad_build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "BRLCAD built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "WIX")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "D:/a/brlcad_winci/brlcad_winci/brlcad_build;BRLCAD;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files/BRL-CAD 7.43.0")
set(CPACK_MODULE_PATH "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake")
set(CPACK_NSIS_DISPLAY_NAME "BRLCAD 7.43.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "BRLCAD 7.43.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "BRL-CAD - a powerful cross-platform open source solid modeling system")
set(CPACK_PACKAGE_FILE_NAME "BRL-CAD_7.43.0_win64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://brlcad.org")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "BRLCAD 7.43.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "BRL-CAD 7.43.0 win64")
set(CPACK_PACKAGE_NAME "BRLCAD")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "BRL-CAD Development Team")
set(CPACK_PACKAGE_VERSION "7.43.0")
set(CPACK_PACKAGE_VERSION_MAJOR "7")
set(CPACK_PACKAGE_VERSION_MINOR "43")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "D:/a/brlcad_winci/brlcad_winci/brlcad_build/BRLCAD_CPackOptions.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "D:/a/brlcad_winci/brlcad_winci/brlcad/COPYING")
set(CPACK_RESOURCE_FILE_README "D:/a/brlcad_winci/brlcad_winci/brlcad/README")
set(CPACK_RESOURCE_FILE_WELCOME "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/share/cmake-4.3/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "\\.git/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "brlcad-7.43.0")
set(CPACK_STRIP_FILES "FALSE")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_LICENSE_RTF "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/wix/License.rtf")
set(CPACK_WIX_PRODUCT_ICON "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/wix/brlcad_product.ico")
set(CPACK_WIX_PROGRAM_MENU_FOLDER "BRL-CAD 7.43.0")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_WIX_UI_BANNER "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/wix/brlcad_banner.bmp")
set(CPACK_WIX_UI_DIALOG "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/wix/brlcad_dialog.bmp")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/a/brlcad_winci/brlcad_winci/brlcad_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
