# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/regress
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress-usage]=] "C:/Program Files/Git/bin/sh.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/regress/usage.sh" "D:/a/brlcad_winci/brlcad_winci/brlcad")
set_tests_properties([=[regress-usage]=] PROPERTIES  LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/CMakeLists.txt;108;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/CMakeLists.txt;0;")
add_test([=[regress-flawfinder]=] "C:/Program Files/Git/bin/sh.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/regress/flawfinder.sh" "D:/a/brlcad_winci/brlcad_winci/brlcad")
set_tests_properties([=[regress-flawfinder]=] PROPERTIES  LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/CMakeLists.txt;112;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/CMakeLists.txt;0;")
subdirs("asc")
subdirs("bots")
subdirs("comgeom")
subdirs("coverage")
subdirs("dsp")
subdirs("fuzz")
subdirs("gdiff")
subdirs("icv")
subdirs("gchecker")
subdirs("ged")
subdirs("gcv")
subdirs("gqa")
subdirs("iges")
subdirs("licenses")
subdirs("lights")
subdirs("mged")
subdirs("moss")
subdirs("nirt")
subdirs("nurbs")
subdirs("pkg")
subdirs("red")
subdirs("repository")
subdirs("rtedge")
subdirs("rtwizard")
subdirs("user")
subdirs("solids")
subdirs("spdi")
subdirs("shaders")
subdirs("weight")
