# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress-pix_pix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-pix_pix.cmake")
set_tests_properties([=[regress-pix_pix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;13;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-png_pix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-png_pix.cmake")
set_tests_properties([=[regress-png_pix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;21;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-pix_png]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-pix_png.cmake")
set_tests_properties([=[regress-pix_png]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;30;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-ppm_pix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-ppm_pix.cmake")
set_tests_properties([=[regress-ppm_pix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;45;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-pix_ppm]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-pix_ppm.cmake")
set_tests_properties([=[regress-pix_ppm]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;54;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-dpix_pix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-dpix_pix.cmake")
set_tests_properties([=[regress-dpix_pix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;69;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-pix_dpix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-pix_dpix.cmake")
set_tests_properties([=[regress-pix_dpix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;78;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-bw_pix]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-bw_pix.cmake")
set_tests_properties([=[regress-bw_pix]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;99;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-pix_bw]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-pix_bw.cmake")
set_tests_properties([=[regress-pix_bw]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;108;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-bw_png]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-bw_png.cmake")
set_tests_properties([=[regress-bw_png]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;117;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
add_test([=[regress-png_bw]=] "D:/a/_temp/-1212469507/cmake-4.3.1-windows-x86_64/bin/cmake.exe" "-DEXEC=D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/icv.exe" "-P" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/regress/icv/regress-png_bw.cmake")
set_tests_properties([=[regress-png_bw]=] PROPERTIES  LABELS "Regression" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;126;brlcad_regression_test;D:/a/brlcad_winci/brlcad_winci/brlcad/regress/icv/CMakeLists.txt;0;")
