# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/src/libged/tests/draw
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ged_test_drawing_basic]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_draw.exe" "-c" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;53;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_faceplate]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_faceplate.exe" "-c" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_faceplate]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;75;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_lod]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_lod.exe" "-c" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_lod]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;94;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_select]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_select_draw.exe" "-c" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_select]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;151;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_quad]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_quad.exe" "-c" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_quad]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;197;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
