# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/src/libged/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ged_test_tops_moss]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_tops.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/ged_tests.g")
set_tests_properties([=[ged_test_tops_moss]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;5;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_list]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_list.exe" "2")
set_tests_properties([=[ged_test_list]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;11;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_material]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_material.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad_build/src/libged/tests/ged_test_material.g")
set_tests_properties([=[ged_test_material]=] PROPERTIES  ENVIRONMENT "BRLCAD_ROOT=D:/a/brlcad_winci/brlcad_winci/brlcad_build" _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;27;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_search]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_test_search.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/search_tests.g")
set_tests_properties([=[ged_test_search]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;42;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[rt_search_tests]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_search_test.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/rt_search_tests.g")
set_tests_properties([=[rt_search_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;48;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_prim_cmds_exist]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/ged_check_prim_cmds.exe")
set_tests_properties([=[ged_test_prim_cmds_exist]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;54;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/libged/tests/CMakeLists.txt;0;")
subdirs("bot")
subdirs("draw")
