# CMake generated Testfile for 
# Source directory: D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests
# Build directory: D:/a/brlcad_winci/brlcad_winci/brlcad_build/src/librt/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[rt_bundle]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/bundle.exe")
set_tests_properties([=[rt_bundle]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;2;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_pattern_5]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_pattern.exe" "5")
set_tests_properties([=[rt_pattern_5]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;7;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_dvec]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_dvec.exe")
set_tests_properties([=[rt_dvec]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;16;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cyclic_basic]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cyclic.exe" "D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/cyclic_tests.g")
set_tests_properties([=[rt_cyclic_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;60;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_single_object]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "1")
set_tests_properties([=[rt_cache_serial_single_object]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;63;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_single_object]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "2")
set_tests_properties([=[rt_cache_parallel_single_object]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;64;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_multiple_identical_objects]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "3" "10")
set_tests_properties([=[rt_cache_serial_multiple_identical_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;65;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_identical_objects]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "4" "10")
set_tests_properties([=[rt_cache_parallel_multiple_identical_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;66;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_multiple_different_objects]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "5" "10")
set_tests_properties([=[rt_cache_serial_multiple_different_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;67;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_different_objects]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "6" "10")
set_tests_properties([=[rt_cache_parallel_multiple_different_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;68;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_different_objects_hierarchy_1]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_cache.exe" "7" "10")
set_tests_properties([=[rt_cache_parallel_multiple_different_objects_hierarchy_1]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;69;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_search_stress]=] "D:/a/brlcad_winci/brlcad_winci/brlcad_build/bin/rt_search_stress.exe")
set_tests_properties([=[rt_search_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;D:/a/brlcad_winci/brlcad_winci/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;83;brlcad_add_test;D:/a/brlcad_winci/brlcad_winci/brlcad/src/librt/tests/CMakeLists.txt;0;")
subdirs("edit")
